NORMAL_ACTIVITY_CHOICES = [
    "ADDBRE","ADDLON","ADDMAG","BICFEM","CALF","EXTDIGLON","EXTHALLON",
    "FLEDIGLON","FLEHALLON","GASTRO","GLUMAX","GLUMED","GLUMIN","GRACIL",
    "HAMSTR","HIPABD","HIPADD","HIPEXT","HIPFLE","ILIACU","ILIOPS","LATHAM",
    "LATQUA","MEDHAM","MEDQUA","PERBRE","PERLON","POPLIT","RECFEM","SARTOR",
    "SEMIME","SEMITE","SOLEUS","TENFACLAT","TIBANT","TIBPOS","VASINT","VASLAT",
    "VASMEDLON","VASMEDOBL",
]