name: docs
channels:
  - conda-forge
  - opensim-org
  - defaults
dependencies:
  - python=3.10
  - numpy >=1.25,<1.26
  - pip
  - btk
  - opensim
  - scipy
  - matplotlib-base
  - pandas
  - pytest
  - pytest-mpl
  - scikit-learn
  - seaborn
  - beautifulsoup4
  - yamlordereddictloader
  - openpyxl
  - lxml
  - myst-parser
  - sphinx
  - sphinx-argparse
  - sphinxcontrib-mermaid
  - pydata-sphinx-theme
  - onnxruntime
  - jinja2