name: Deploy Documentation

on:
  push:
    branches:
      - Master  

jobs:
  build-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: pycgm310
          environment-file: environment.yml
          auto-activate-base: false

      - name: Create Conda environment
        shell: cmd
        run: |
          conda env remove --name pycgm310 --yes || echo "env does not exist"
          conda env create --file environment.yml --name pycgm310

      - name: Activate Conda and build docs
        shell: cmd
        run: |
          call activate pycgm310
          sphinx-build -b html docs/ docs/_build/html

      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
